### ISSUE TITLE
Add support for missing rosinstall dependencies

### ISSUE THREAD

**Issue by ChrisTimperley** [robust-rosin/robust#150]
See #126, #131, #127, #128. 

Possible approaches:

1. Each bug provides its own `deps.rosinstall.diff` patch file, which is applied to `deps.rosinstall` to obtain a complete list of dependencies. Has a number of cons: (1) tedious to determine appropriate versions, especially for recursive cases, (2) requires that we add a no-op file to every bug directory to ensure that bugs build, (3) more complicated (and needlessly so) than simply giving a list of additional dependencies.
2. Each bug provides its own `extra.rosinstall` file, which provides a `rosintall` file containing all of the missing dependencies. Slightly nicer than (1) but still tedious and introduces additional files.
3. Update `time-machine` section in bug description file to contain a list that details the missing dependencies for a particular bug:
```
missing-dependencies:
  - tar:
    local-name: actionlib
    uri: https://github.com/ros-gbp/actionlib-release/archive/release/hydro/actionlib/1.10.3-0.tar.gz
    version: actionlib-release-release-hydro-actionlib-1.10.3-0
```
  The contents of the `missing-dependencies` section can then either be automatically written to `extra.rosinstall` or folded into `deps.rosinstall`.
4. Update `time-machine` section in bug description file to state the names of the missing dependencies:
```
missing-dependencies:
  - actionlib
```
The time machine helper script, `build-time-machine.py`, should query the time machine to determine the most appropriate release of each missing dependency (along with any recursive dependencies). The complete set of dependencies should be folded into `deps.rosinstall`.
