### ISSUE TITLE
Parsing of bug description for bugzoo

### ISSUE THREAD

**Issue by ipa-jfh** [robust-rosin/robust#165]
Sry if I missed any discussion about this.
@ChrisTimperley 
Using `build-bugzoo.py` and then showing the bug list results to
(I am happy that the bug appeared in the list :blush:)

```bash
$ bugzoo bug list
# Bug                Program       Dataset    Source     Installed?
# -----------------  ------------  ----------  ------------  ------------
# robust:description  105dc16       robust     robustpy3  No
```

By design the program would parse the hash out of the bug-filename, which did not work for me as I renamed it to "description.bug". In the example above we got the hash through the folder name, which I would like to avoid. Furthermore, the short hash is not saved in the ".bug" file. 

My question is if we should parse folder and/or file names or not? (If yes, we have to enforce a strict file structure).

I would personally suggest the following:

```
# Bug                       Program          Dataset    Source     Installed?
# ----------------------  ---------------  ----------  ------------  ------------
# robust:105dc16          cob_control        robust     robustpy3  No
# robust:<filename>       <ros_pkgs>      ...
```
Again this would get complicated if `ros_pkgs` would be a list.

Relevant part of the `description.bug`

```yaml
time-machine:
  ros_distro: indigo
  ros_pkgs:
    - cob_control
  issue: https://github.com/ipa320/cob_control/issues/6
bugzoo:
  fork-url: https://github.com/robust-rosin/cob_control
  is-build-failure: yes
  bug-commit: 105dc16_robust_buggy
  fix-commit: 105dc16_robust_fixed
```

Relevant part of the `robust.bugzoo.yml`:

```yaml
blueprints:
- arguments:
    CATKIN_PKG: cob_control
    IS_BUILD_FAILURE: 'yes'
    REPO_BUG_COMMIT: 105dc16_robust_buggy
    REPO_FIX_COMMIT: 105dc16_robust_fixed
    REPO_FORK_URL: https://github.com/robust-rosin/cob_control
    ROS_DISTRO: indigo
    UBUNTU_VERSION: 14.04.5
    USE_APT_OLD_RELEASES: false
    USE_OSRF_REPOS: false
  context: care-o-bot/description
  file: Dockerfile
  tag: robustrosin/robust:description
```

**Comment by ChrisTimperley** [comment]
Requiring that the short hash is provided as part of the `.bug` file is probably the best idea. The `program` section of BugZoo is really only there for the sake of convenience, so I don't think it would hurt if we simply used the name of the first PUT.

**Comment by ChrisTimperley** [comment]
Having said that, I do believe that we should maintain a consistent file structuring, for the sake of ourselves and others, whatever that structure may be.

**Comment by ipa-jfh** [comment]
We could parse the short hash out of the long one from the bug description.

```yaml
fix:
  repo: https://github.com/mavlink/mavros
  hash: 27e7db9d504359d05830fbc9553fd1fd1af3aab2
```

Then every info is taken out of the `.bug` file and the file structure is not critical.

> Having said that, I do believe that we should maintain a consistent file structuring, for the sake of ourselves and others, whatever that structure may be.

https://github.com/robust-rosin/robust/issues/169
