### ISSUE TITLE
Taxonomy: reproduction-images

### ISSUE THREAD

**Issue by git-afsantos** [robust-rosin/robust#259]
Regarding the `buggy` and `fixed` sub-properties of `reproduction-images`, the taxonomy says:

```yaml
reproduction-images:
  buggy: the nearest compiling commit in git log that exhibits the bug (an anecstor of the fixing commit)
  fixed: the neaerst compiling commit that contains the fix (a child of the fixing commit)
```

Are these hashes from the original PUT, or from our fork (i.e., the most up-to-date hashes for the test cases)?
