### ISSUE TITLE
building care-o-bot 79867c8

### ISSUE THREAD

**Issue by ipa-hsd** [robust-rosin/robust#262]
While building the [bug](https://github.com/robust-rosin/robust/blob/master/care-o-bot/79867c8/79867c8.bug), I get the following error:

```
Updating local rosdistro index.yaml to use cache from the past ..
Invoking: rosinstall_generator --rosdistro=indigo cob_android --deps --tar --deps-only
Using ROS_DISTRO: indigo
The following not released packages/stacks will be ignored: cob_android
No packages/stacks left after ignoring not released
Traceback (most recent call last):
  File "scripts/build-rosinstall.py", line 57, in _time_machine
    stdout=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rosinstall_generator_tm.sh', '2015-08-03T08:03:34Z', 'indigo', 'cob_android', '--deps', '--tar', '--deps-only']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/build-rosinstall.py", line 173, in <module>
    main()
  File "scripts/build-rosinstall.py", line 166, in main
    build_file(fn_or_dir, overwrite=args.overwrite)
  File "scripts/build-rosinstall.py", line 118, in build_file
    deps.update(_time_machine(ros_pkgs, dt, distro, deps_only=True))
  File "scripts/build-rosinstall.py", line 61, in _time_machine
    err.returncode, fn_bug_desc)
NameError: name 'fn_bug_desc' is not defined
```
The issue was created at `2015-08-03T08:03:34Z` and the package was first released on [Aug 29, 2015](https://github.com/ipa320/cob_android/releases). So basically, there is no entry of this package for the requested `{TIMEPOINT}` in rosdistro.

How can we solve this?

**Comment by git-afsantos** [comment]
I think I ran into a similar issue once or twice before, and I think there is no alternative other than using the release date of the package. But perhaps, someone else has a better solution.

**Comment by ipa-hsd** [comment]
The issue was already [fixed](https://github.com/ipa320/cob_android/pull/8) before the 1st release.

**Comment by gavanderhoorn** [comment]
Related: https://github.com/rosin-project/rosinstall_generator_time_machine/issues/11.

**Comment by ipa-hsd** [comment]
Should I close this, since it is being tracked elsewhere?

**Comment by gavanderhoorn** [comment]
Well, the issue of repositories using source builds and reporting bugs in those is tracked in other issues.

But your problem reproducing `79867c8` is not.

What I would recommend is the following: generate a `.rosinstall` file using the first released version (to get all the dependencies in place) and then continue with the commit hash of the unfixed version (ie: the one that was not released).

That should work.

We should make a note about this (ie: not using the "correct" timepoint).

**Comment by ipa-hsd** [comment]
I was able to generate `deps.rosinstall` from the following command:
```
rosinstall_generator_tm.sh 2015-08-30T08:03:34Z indigo cob_android --deps --deps-only --tar > deps.rosinstall
```
I guess now I have to modify the `cob_android` package entries manually to `79867c8`.

**Comment by gavanderhoorn** [comment]
> I guess now I have to modify the `cob_android` package entries manually to `79867c8`.

yes, if that is the hash for the buggy state, then that would be the idea :)

**Comment by ipa-hsd** [comment]
These are the `cob_android` package entries in the `deps.rosinstall`:
```
- tar:
    local-name: cob_android/cob_android_msgs
    uri: https://github.com/ipa320/cob_android-release/archive/release/indigo/cob_android_msgs/0.1.1-0.tar.gz
    version: cob_android-release-release-indigo-cob_android_msgs-0.1.1-0
- tar:
    local-name: cob_android/cob_android_resource_server
    uri: https://github.com/ipa320/cob_android-release/archive/release/indigo/cob_android_resource_server/0.1.1-0.tar.gz
    version: cob_android-release-release-indigo-cob_android_resource_server-0.1.1-0
- tar:
    local-name: cob_android/cob_android_script_server
    uri: https://github.com/ipa320/cob_android-release/archive/release/indigo/cob_android_script_server/0.1.1-0.tar.gz
    version: cob_android-release-release-indigo-cob_android_script_server-0.1.1-0
- tar:
    local-name: cob_android/cob_android_settings
    uri: https://github.com/ipa320/cob_android-release/archive/release/indigo/cob_android_settings/0.1.1-0.tar.gz
    version: cob_android-release-release-indigo-cob_android_settings-0.1.1-0
```

**Comment by gavanderhoorn** [comment]
`cob_android` is a metapackage, so cannot actually be the package any bug with `install(..)` statements is in.

Looking at the bug description, it would appear the affected packages are `cob_android_msgs` and `cob_android_script_server` ([here](https://github.com/robust-rosin/robust/blob/c01a6d3f8279996b10b6d99c4aa471bbfcae70bd/care-o-bot/79867c8/79867c8.bug#L54)). Those packages should be passed to the time machine, not the metapackage.

**Comment by gavanderhoorn** [comment]
Note: the bug description would seem to be incorrect. The bug is not in `cob_android`, but in those other packages. [This line](https://github.com/robust-rosin/robust/blob/c01a6d3f8279996b10b6d99c4aa471bbfcae70bd/care-o-bot/79867c8/79867c8.bug#L41) should probably be updated.

**Comment by ipa-hsd** [comment]
Can someone give me permissions to fork repositories to this organization?

**Comment by gavanderhoorn** [comment]
No (as it's not a permission we can give to individual users), but we can invite you to the `robust-rosin` organisation. Which I just did.

**Comment by ipa-hsd** [comment]
I don't remember if @ChrisTimperley said if bugzoo can handle multiple PUTs yesterday, but the bug file looks like this:

```
bug:
  package: cob_android_msgs cob_android_script_server
  issue: https://github.com/ipa320/cob_android/issues/7
  time-reported: 2015-08-03 (10:09)
time-machine:
  ros_distro: indigo
  ros_pkgs:
    - cob_android_msgs
    - cob_android_script_server
  issue: https://github.com/ipa320/cob_android/issues/7
bugzoo:
  fork-urls: https://github.com/robust-rosin/cob_android
  bug-commit: 21126f5e3d2e15ae8c93705dc3e8e999707da48e
  fix-commit: 79867c88acc64342f061e6324ed6b84ca7e0773d
```
And the output of 
```
 python build-bugzoo.py
```
is 
```
generating manifest for bug file [care-o-bot/79867c8/79867c8.bug]
build-bugzoo.py:71: UserWarning: BugZoo file does not currently support multiple PUTs
  warnings.warn('BugZoo file does not currently support multiple PUTs')
```

**Comment by gavanderhoorn** [comment]
IIRC, BugZoo: not tested (probably not). The `.rosinstall` script: most likely yes.

**Comment by ChrisTimperley** [comment]
> ```
> generating manifest for bug file [care-o-bot/79867c8/79867c8.bug]
> build-bugzoo.py:71: UserWarning: BugZoo file does not currently support multiple PUTs
>   warnings.warn('BugZoo file does not currently support multiple PUTs')
> ```

#264 should add multiple PUT support to `build-bugzoo.py.

Also, `fork-urls` should be a list:

```
bugzoo:
  fork-urls:
    - https://github.com/robust-rosin/cob_android
```

**Comment by ipa-hsd** [comment]
@ChrisTimperley I am able to build the manifest with https://github.com/robust-rosin/robust/pull/264. Thanks!

Now facing https://github.com/robust-rosin/robust/issues/69

**Comment by gavanderhoorn** [comment]
> Now facing #69

#69? Can you show the build log for your bug?

Has the `care-o-bot` repository been renamed? Renames of `geometry_experimental` should be automatically handled.

Could it be that you're running into vcstools/vcstools#147?

**Comment by ipa-hsd** [comment]
@gavanderhoorn : Sorry that was a hasty reply as I didn't dig into the error.

I am getting similar errors for `tf2` related packages:
```
ERROR [vcstools] Tarball download unpack failed: u"geometry_experimental-release-release-indigo-tf2-0.5.12-0 is not a subdirectory with contents in members [u'geometry2-release-release-indigo-tf2-0.5.12-0']"[/vcstools]
```
```
ERROR in config: Error processing 'geometry_experimental/tf2' : [geometry_experimental/tf2] Checkout of https://github.com/ros-gbp/geometry_experimental-release/archive/release/indigo/tf2/0.5.12-0.tar.gz version geometry_experimental-release-release-indigo-tf2-0.5.12-0 into /ros_ws/src/geometry_experimental/tf2 failed.
```

**Comment by gavanderhoorn** [comment]
That would seem to be #69, but afaik we're already handling that with automatic renames of entries in `.rosinstall` files.

Can you clarify which versions of things you are using, and which commands lead to this error?

**Comment by ipa-hsd** [comment]
I pulled https://github.com/robust-rosin/robust/pull/264 in a new branch and working on it.

These are the tars in deps.rosinstall which fail:
```
- tar:
    local-name: geometry_experimental/tf2
    uri: https://github.com/ros-gbp/geometry_experimental-release/archive/release/indigo/tf2/0.5.12-0.tar.gz
    version: geometry_experimental-release-release-indigo-tf2-0.5.12-0
- tar:
    local-name: geometry_experimental/tf2_msgs
    uri: https://github.com/ros-gbp/geometry_experimental-release/archive/release/indigo/tf2_msgs/0.5.12-0.tar.gz
    version: geometry_experimental-release-release-indigo-tf2_msgs-0.5.12-0
- tar:
    local-name: geometry_experimental/tf2_py
    uri: https://github.com/ros-gbp/geometry_experimental-release/archive/release/indigo/tf2_py/0.5.12-0.tar.gz
    version: geometry_experimental-release-release-indigo-tf2_py-0.5.12-0
- tar:
    local-name: geometry_experimental/tf2_ros
    uri: https://github.com/ros-gbp/geometry_experimental-release/archive/release/indigo/tf2_ros/0.5.12-0.tar.gz
    version: geometry_experimental-release-release-indigo-tf2_ros-0.5.12-0
```

The following command lead to the error:
```
bugzoo bug build --force robust:79867c8
```
