### ISSUE TITLE
Bugzoo fails to build c779432

### ISSUE THREAD

**Issue by git-afsantos** [robust-rosin/robust#279]
Bugzoo data:

```yaml
bugzoo:
  fork-urls: 
    - https://github.com/robust-rosin/universal_robot
  is-build-failure: yes
  use-osrf: no  # [optional]
  bug-commit: 7958c81afed1d70322efbd84aa042ddfaf2c54ea
  fix-commit: c7794329bf632592bf1d345d1290ff4b8d13580a
```

Command:

```bash
bugzoo bug build --force robust:c779432 2>&1 | tee universal_robot/c779432/build.log
```

Error:

> E: Unable to locate package libfcl-0.5-dev
> E: Couldn't find any package by glob 'libfcl-0.5-dev'
> E: Couldn't find any package by regex 'libfcl-0.5-dev'
> ERROR: the following rosdeps failed to install
>   apt: command [apt-get install -y libfcl-0.5-dev] failed

Log (will remove it from the repository later):
https://github.com/robust-rosin/robust/blob/ec9906a79e954fa42179ba8779eb0fe4508df2de/universal_robot/c779432/build.log
